# Generated by Django 5.0.6 on 2024-06-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
