# Generated by Django 5.0.6 on 2024-06-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
