# Generated by Django 5.0.6 on 2024-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lessons/previews",
                verbose_name="превью урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lessons/videos",
                verbose_name="видео урока",
            ),
        ),
    ]
